[[Xorg_libxkbfile]]
arch = "armv7l"
git-tree-sha1 = "f8c6eb2258a0fccceff7bf5887d7f953bef9c1a5"
libc = "glibc"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "dfe91b5cd861aee4df9a0e668044dd0b1fb485340f37e39d8252e64efe9c7edb"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+2/Xorg_libxkbfile.v1.1.0.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libxkbfile]]
arch = "i686"
git-tree-sha1 = "a784aa33e06dff6254d56fe85200e116934e28f5"
libc = "musl"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "a41824ab3c8982c512f4336d29255a1e80d6a4feefde97203d5b2c9c4ba8359c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+2/Xorg_libxkbfile.v1.1.0.i686-linux-musl.tar.gz"
[[Xorg_libxkbfile]]
arch = "aarch64"
git-tree-sha1 = "1d0347cc90bc881f9dda890d6e10dbbbd27c291b"
libc = "glibc"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "3c04b6a77f0cbb58806bc17e30c600b4aedc27a1afda7a877ae04e3be1ece947"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+2/Xorg_libxkbfile.v1.1.0.aarch64-linux-gnu.tar.gz"
[[Xorg_libxkbfile]]
arch = "armv7l"
git-tree-sha1 = "63ef634adf8db2feffccf81b2c78d3aa2f3511e5"
libc = "musl"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "703acf23d8fbbe71eb951e8c3047c72e610f039742c028dc0424b921237473a4"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+2/Xorg_libxkbfile.v1.1.0.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libxkbfile]]
arch = "aarch64"
git-tree-sha1 = "9629af0f7c0130780f6f174c94d80f83259ec763"
libc = "musl"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "6e58c0d8c04c7a62ea65dc3ad4d9bc1b4dd4be1947de1eb5c6d6e95e6eddc2b6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+2/Xorg_libxkbfile.v1.1.0.aarch64-linux-musl.tar.gz"
[[Xorg_libxkbfile]]
arch = "x86_64"
git-tree-sha1 = "c75dff101661891dcfae624d0be8ea364db3dd1d"
os = "freebsd"

    [[Xorg_libxkbfile.download]]
    sha256 = "570e71dcee91c7ee9327957f3ab2c6a4352905c9088a551ace045ec47e5be97a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+2/Xorg_libxkbfile.v1.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_libxkbfile]]
arch = "i686"
git-tree-sha1 = "08078c057b53b12f2fa8ba03a88891f43b6d83bb"
libc = "glibc"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "71d05d6959e7cec611ae3e59b0602ea19b54860312285b0167b501721000d875"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+2/Xorg_libxkbfile.v1.1.0.i686-linux-gnu.tar.gz"
[[Xorg_libxkbfile]]
arch = "x86_64"
git-tree-sha1 = "c44e0bc2182097d57eb42a6d91a877fc7df11ac8"
libc = "musl"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "146c7df3400f733c16a3ab49ad683c07c65f92f1c6480ea322b5b55ccec09518"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+2/Xorg_libxkbfile.v1.1.0.x86_64-linux-musl.tar.gz"
[[Xorg_libxkbfile]]
arch = "x86_64"
git-tree-sha1 = "4ff195495c83d25c4f6457d0073965585b98fd24"
libc = "glibc"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "d6217417755ad73cccf721fc0710d11b21035042ede7be3659fe5ab6507dc543"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+2/Xorg_libxkbfile.v1.1.0.x86_64-linux-gnu.tar.gz"
[[Xorg_libxkbfile]]
arch = "powerpc64le"
git-tree-sha1 = "288aad042f5291752b1153a9722648440f353c7a"
libc = "glibc"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "92a81d4339b134c28a9b64780613f80b390e0100b019ad84ffa63c8070701e74"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+2/Xorg_libxkbfile.v1.1.0.powerpc64le-linux-gnu.tar.gz"
