[[Xorg_libxkbfile]]
arch = "aarch64"
git-tree-sha1 = "5df4e3d683a326b2d4692ce3d1c65fb738276fbe"
libc = "glibc"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "8caa8b2d3298c29debefa80e14533a893cd01a70014019c8d1f15d7f389a0e6b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.3+0/Xorg_libxkbfile.v1.1.3.aarch64-linux-gnu.tar.gz"
[[Xorg_libxkbfile]]
arch = "aarch64"
git-tree-sha1 = "d6351ded5f2a88d57de9e49a218d60a775cadd9a"
libc = "musl"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "c7d05914dc593723f8f22b48545492727fd82f7164c13c3135869805d4ed8c31"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.3+0/Xorg_libxkbfile.v1.1.3.aarch64-linux-musl.tar.gz"
[[Xorg_libxkbfile]]
arch = "aarch64"
git-tree-sha1 = "47c5d31887e5308e43da3d2e09cc33efd538b355"
os = "freebsd"

    [[Xorg_libxkbfile.download]]
    sha256 = "e596ecf48fa5ea28187603ef6177308f78e82cdf79918ee26757819eb8b1d19f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.3+0/Xorg_libxkbfile.v1.1.3.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libxkbfile]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "58b16a7537f0dbad45d9affd0fc241a7f0a9cbd3"
libc = "glibc"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "b77b91dd3fd21f0fbf252611d0b577e0d32f03147d663ff95b81645d15c96edf"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.3+0/Xorg_libxkbfile.v1.1.3.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libxkbfile]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f20db48f2f40170bd29fbf6a2cb3fe76ac250c95"
libc = "musl"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "93d63cfc0c69e4185dece56721cac52b01ea0e86276b768718c12b2724467ba3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.3+0/Xorg_libxkbfile.v1.1.3.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libxkbfile]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b9b55da85a25503e3d57c36d0ba63a13b7465e46"
libc = "glibc"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "dda05a0cce9a6f843b7e9bf6c66a00b966b387ded88f87fe2f6877e2822a8f33"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.3+0/Xorg_libxkbfile.v1.1.3.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libxkbfile]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bf51290e1a8cfcff8709384696c9eef71baa076f"
libc = "musl"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "f829eafd1fa6dac25584249cb429fdb74f7ddf0aa4239013a1c6a431f1589337"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.3+0/Xorg_libxkbfile.v1.1.3.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libxkbfile]]
arch = "i686"
git-tree-sha1 = "9a3aa9f4b4ccac077d39914d1fd14cddd5ddb626"
libc = "glibc"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "aafe0d0914a2972903f085224e0e57da4618419462fa785ac6cc3af9bba38e0f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.3+0/Xorg_libxkbfile.v1.1.3.i686-linux-gnu.tar.gz"
[[Xorg_libxkbfile]]
arch = "i686"
git-tree-sha1 = "a4961ff4a892428315cad142b6f7f6088e0f66a9"
libc = "musl"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "ba347a8b3f1ca7e8b1be733291829d0e509d7baf2ac39da852c15bdc0a2b6dbd"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.3+0/Xorg_libxkbfile.v1.1.3.i686-linux-musl.tar.gz"
[[Xorg_libxkbfile]]
arch = "powerpc64le"
git-tree-sha1 = "95a987e20f090da190cdeaaf31c2df451db644f0"
libc = "glibc"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "8d61c6e1d998bc81daef13892637bb61891cf121a5f79646604ef63df7ea44cf"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.3+0/Xorg_libxkbfile.v1.1.3.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libxkbfile]]
arch = "riscv64"
git-tree-sha1 = "74ddafaf3efb870ec40f9bda062dc175248499dd"
libc = "glibc"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "7335ddc3b2b03d19cad3823671c61cac00a0ec183697a486a302e81472fc0b8b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.3+0/Xorg_libxkbfile.v1.1.3.riscv64-linux-gnu.tar.gz"
[[Xorg_libxkbfile]]
arch = "x86_64"
git-tree-sha1 = "d007148a0838385ad09a5cc9f703679ddaffcf0b"
libc = "glibc"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "974ad6afbc9d67b72fe3fd6a4b8b297782a21819bbcc16d6fb31ca220e82b90c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.3+0/Xorg_libxkbfile.v1.1.3.x86_64-linux-gnu.tar.gz"
[[Xorg_libxkbfile]]
arch = "x86_64"
git-tree-sha1 = "7a8967f67cb506fdf13e31e71a6712e89a0b5417"
libc = "musl"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "39900e000e6756274c96283eef13235637b5274a1a66966e7115f426851673d8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.3+0/Xorg_libxkbfile.v1.1.3.x86_64-linux-musl.tar.gz"
[[Xorg_libxkbfile]]
arch = "x86_64"
git-tree-sha1 = "b2d77dc44da8ca1a941c1de5a3beb5330636ef1e"
os = "freebsd"

    [[Xorg_libxkbfile.download]]
    sha256 = "94aeba4925aa3b2c609947f22faa4d5936d5cf03b5d9074e26d564c0ad078a33"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.3+0/Xorg_libxkbfile.v1.1.3.x86_64-unknown-freebsd.tar.gz"
