[[Xorg_libxkbfile]]
arch = "aarch64"
git-tree-sha1 = "54aa7f36fd2c220aa5a5d5910a710135a8d3640e"
libc = "musl"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "9d2b123e66b3022ed9b9b039d2e35872cc35a744924ff6536dce48998e8f157b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+1/Xorg_libxkbfile.v1.1.0.aarch64-linux-musl.tar.gz"
[[Xorg_libxkbfile]]
arch = "aarch64"
git-tree-sha1 = "76fc55806d4ac2c5bfe4e2e937fefa98d83e7b32"
libc = "glibc"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "6a20716afc9847bfe0a8613fb55a5ddb43d834c59df99b54ebb0d9033efe2cad"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+1/Xorg_libxkbfile.v1.1.0.aarch64-linux-gnu.tar.gz"
[[Xorg_libxkbfile]]
arch = "x86_64"
git-tree-sha1 = "fa2317cc81ae934ce40b14d9ce60d9d0b7ea33f3"
libc = "glibc"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "2ba6364820bac11945f7ff3c48b3fecd5f8c6c50ccd7c219b7f41f285296b153"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+1/Xorg_libxkbfile.v1.1.0.x86_64-linux-gnu.tar.gz"
[[Xorg_libxkbfile]]
arch = "powerpc64le"
git-tree-sha1 = "9fa308c100604b280365355a58b9bc42ff705ffc"
libc = "glibc"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "da4602f0134bf3184b9c2aa4d936357bbe8588131db283125ed9f2d4c6f04b50"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+1/Xorg_libxkbfile.v1.1.0.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libxkbfile]]
arch = "x86_64"
git-tree-sha1 = "a536fce175556cf763b742ca877cd26eb15580a6"
os = "freebsd"

    [[Xorg_libxkbfile.download]]
    sha256 = "329bcc29f90caef5a2f18e54e3d3af5756c6be27ce6127b703f6e485db571a48"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+1/Xorg_libxkbfile.v1.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_libxkbfile]]
arch = "i686"
git-tree-sha1 = "951e4037754b182a47d5e4bf060323abe403366c"
libc = "glibc"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "d40d5d6169fc8b16a7f55168c068d7230b28d5d9747a2cfe0d49c71aa452534f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+1/Xorg_libxkbfile.v1.1.0.i686-linux-gnu.tar.gz"
[[Xorg_libxkbfile]]
arch = "i686"
git-tree-sha1 = "62f9fc9c29a5259c983b21c5d637ff34e3af95e4"
libc = "musl"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "d5538a5acb9f7711c9b41d9cc1a396b6621c3263ae3efa508a1c4255283d12dd"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+1/Xorg_libxkbfile.v1.1.0.i686-linux-musl.tar.gz"
[[Xorg_libxkbfile]]
arch = "armv7l"
git-tree-sha1 = "55a2d1d21359b479e73d8e056ec9111c3b0d8e1f"
libc = "glibc"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "5859d046855e2ded8b7c327f8a9547e08385248087ed639adb1b1fa948e4669f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+1/Xorg_libxkbfile.v1.1.0.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libxkbfile]]
arch = "x86_64"
git-tree-sha1 = "8f3eed89674c3a3b41939566f6be7f12d9051b8f"
libc = "musl"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "2b72da7f1e3729e2c7277c494be01c7c4decc079a280ca355960b7eec0a45a8e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+1/Xorg_libxkbfile.v1.1.0.x86_64-linux-musl.tar.gz"
[[Xorg_libxkbfile]]
arch = "armv7l"
git-tree-sha1 = "4d4692641c545f90b2f042211274e99674783c6c"
libc = "musl"
os = "linux"

    [[Xorg_libxkbfile.download]]
    sha256 = "bf8fa3c2434ca4c24f9188445574694be9de5efdb994a9627de41029b8e149bc"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+1/Xorg_libxkbfile.v1.1.0.armv7l-linux-musleabihf.tar.gz"
